spring:
  datasource:
    username: root
    password: Concho123
    url: jdbc:mysql://localhost:3306/hieugiay
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: "hieudoo213@gmail.com"
    password: "ypkjudjcnfjrkxgo"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    session:
      cookie:
        same-site: strict

project:
  image: image/

base:
  url: "http://localhost:8080"

